config/routes.rb
Rails.application.routes.draw do

  root "charges#index"

  resources :charges, only:[:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/charge.rb
class Charge < ApplicationRecord

    enum status: [:created, :pending, :paid, :rejected, :error, ]
    enum payment_method: [:unknown, :credit_card, :debit_card, :pse, :cash, :referenced]

    before_create :generate_uid


    private 

    def generate_uid
        begin
        self.uid = SecureRandom.hex(5)
        end while self.class.exists?(uid: self.uid)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

    def index 
        @charges = Charge.all
    end

    def new 
        @charge = Charge.new
    end

    def create
        charge = Charge.new(charge_params)
        if charge.save
            redirect_to root_path
        else
            render :new
        end
    end

    private
    
    def charge_params
        params.require(:charge).permit(:anount)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/index.html.erb
<div class="container">
    <div class="row">
        <div class="col">
        <button class=""><%= link_to "Nuevo cobro", new_charge_path%></button>

        <table class="table mt-3">
            <thead>
                <tr>
                    <th>Fecha</th>
                    <th>Referencia</th>
                    <th>Valor</th>
                    <th>Estado</th>
                    <th>Metodo de pago</th>
                </tr>
            </thead>
            <tbody>
                <% @charges.each do |charge| %>
                <tr>
                    <td><%= charge.created_at%></td>
                    <td><%= charge.uid%></td>
                    <td><%= charge.anount%></td>
                    <td>
                        <%= charge.status %>
                        <% if charge.error_message %>
                            <%= charge.error_message %>
                        <% end %>
                    </td>
                    <td><%= charge.payment_method %></td>
                </tr>
                <%end%>
            </tbody>
        </table>
        </div>
    </div>
</div>

app/views/charges/new.html.erb
<div class="col-5">
    <%= form_for @charge do |f| %>
        <div class= "fomr-group">
            <%= f.label :anount%>
            <%= f.text_field :anount, class: "form_control"%>
        </div>
        <div>
            <%= link_to "Cancel", root_path%>
            <%= f.submit "Ir a pagar"%>
        <div>
    <%end%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Payments</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>